[[clients-ubuntu]]
= Registering {ubuntu} 20.04 Clients

This section contains information about registering Salt clients running {ubuntu} 20.04 LTS operating systems.

ifeval::[{suma-content} == true]
{productname} supports {ubuntu} 16.04 LTS, 18.04 LTS, and 20.04 LTS clients using Salt.
For information about registering Salt clients running {ubuntu} 16.04 LTS and 18.04 LTS, see xref:client-configuration/clients-ubuntu-old.adoc[].
endif::[]

<<<<<<< HEAD
{susemgr} supports {ubuntu} 16.04 LTS and 18.04 LTS Clients using Salt.
=======
>>>>>>> 4fd527fc... Updates for Ubuntu 20.04 (#243)
Traditional clients are not supported.

[IMPORTANT]
====
Canonical does not endorse or support {susemgr}.
====


Supported features:

* Bootstrapping
* Synchronizing [systemitem]``.deb`` channels
* Assigning [systemitem]``.deb`` channels to clients
* GPG signing [systemitem]``.deb`` repositories
* Information displayed in System details pages
* Package install, update, and remove
* Package install using [systemitem]``Package States``
* Configuration and state channels

Bootstrapping is supported for starting {ubuntu} clients and performing initial state runs such as setting repositories and performing profile updates.

However, the root user on {ubuntu} is disabled by default, so in order to use bootstrapping, you will require an existing user with [command]``sudo`` privileges for Python.

Some actions are not yet supported:

* Patch and errata support
* Bare metal installations, PXE booting, and virtual host provisioning
* Live patching
* CVE Audit
* If you use are using a repository from storage media (`server.susemanager.fromdir = ...` option in rhn.conf), Ubuntu Client Tools will not work.
// Reason: RMT and SMT cannot mirror Debian repositories (yet) and so cannot create it in that directory the correct files.
// We are waiting for SMT to release the feature/fix to mirror Debian repositories. When this has been done, this comment and the limitation above can be removed.




== Prepare to Register

Some preparation is required before you can register {ubuntu} clients to the {productname} Server.


ifeval::[{suma-content} == true]
.Procedure: Adding Client Tools Channels

Before you begin, ensure you have the {ubuntu} product enabled, and have synchronized the {ubuntu} channels for {scc}:

<<<<<<< HEAD
For {ubuntu} 16.04:
=======
You can do this from {webui} or using command prompt, at your choice.

For {ubuntu} 20.04:
>>>>>>> 4fd527fc... Updates for Ubuntu 20.04 (#243)

* From the {webui}, add [systemitem]``Ubuntu 20.04`` and [systemitem]``SUSE Linux Enterprise Client Tools Ubuntu 2004 amd64``.
* From the command prompt, add [systemitem]``ubuntu-20.04-pool-amd64`` and [systemitem]``ubuntu-20.04-suse-manager-tools-amd64``.

In the {productname} {webui}, navigate to menu:Software[Channel List > All].
Verify that you have a base channel and a child channel for your architecture.

<<<<<<< HEAD
For example:

* Base channel: [systemitem]``ubuntu-18.04-pool for amd64``
* Child channel: [systemitem]``Ubuntu-18.04-SUSE-Manager-Tools for amd64``

.Procedure: Creating Custom Repositories

. On the {productname} Server {webui}, navigate to menu:Software[Manage > Repositories].
. Click btn:[Create Repository] and set these parameters for the ``main`` repository:
* In the [guimenu]``Repository Label`` field, type [systemitem]``ubuntu-bionic-main``.
* In the [guimenu]``Repository URL`` field, type [systemitem]``http://ubuntumirror.example.com/ubuntu/dists/bionic/main/binary-amd64/``.
* In the [guimenu]``Repository Type`` field, select [systemitem]``deb``.
* Leave all other fields as the default values.
. Click btn:[Create Repository]
. Click btn:[Create Repository] and set these parameters for the ``main-updates`` repository:
* In the [guimenu]``Repository Label`` field, type [systemitem]``ubuntu-bionic-main-updates``.
* In the [guimenu]``Repository URL`` field, type [systemitem]``http://ubuntumirror.example.com/ubuntu/dists/bionic-updates/main/binary-amd64/``.
* In the [guimenu]``Repository Type`` field, select [systemitem]``deb``.
* Leave all other fields as the default values.
. Click btn:[Create Repository].

When you have created the repositories, you can create the custom channels.

Ensure the custom channels you create have `AMD64 Debian` architecture.

Your custom channels should use this structure:

* Parent channel: [systemitem]``ubuntu-18.04-pool for amd64``
* Child vendor channel: [systemitem]``Ubuntu-18.04-SUSE-Manager-Tools for amd64``
* Child custom channel: [systemitem]``ubuntu-18.04-amd64-main``
* Child custom channel: [systemitem]``ubuntu-18.04-amd64-main-updates``

When you have the channels set up, associate each channel with the appropriate repository, and synchronize then channels.

[IMPORTANT]
====
You need all the new channels fully syncronized before bootstraping any Ubuntu client.
====
endif::[]


ifeval::[{uyuni-content} == true]
=======
For example, for {ubuntu} 20.04:

* Base channel: [systemitem]``ubuntu-2004-amd64-main for amd64``
* Child channel: [systemitem]``Ubuntu-20.04-SUSE-Manager-Tools for amd64``
>>>>>>> 4fd527fc... Updates for Ubuntu 20.04 (#243)

// Uyuni specific instructions, in fact this works at SUSE Manager as well, but spacewalk-common-channels script is NOT supported

.Procedure: Adding the {ubuntu} Channels

<<<<<<< HEAD
. At the command prompt on the {productname} Server, as root, install the [systemitem]``spacewalk-utils`` package:
+
----
sudo zypper in spacewalk-utils
----
. Add the {ubuntu} channels.
Adjust the version of the channel names to match your {ubuntu} version:
+
----
sudo spacewalk-common-channels ubuntu-1804-pool-amd64-uyuni \
ubuntu-1804-amd64-main-uyuni \
ubuntu-1804-amd64-main-updates-uyuni \
ubuntu-1804-amd64-main-security-uyuni \
ubuntu-1804-amd64-universe-uyuni \
ubuntu-1804-amd64-universe-updates-uyuni \
ubuntu-1804-amd64-uyuni-client
=======
. At the command prompt on the {productname} Server, as root, add the {ubuntu} channels.

For {ubuntu} 20.04:
----
spacewalk-common-channels \
ubuntu-2004-pool-amd64-uyuni \
ubuntu-2004-amd64-main-uyuni \
ubuntu-2004-amd64-main-updates-uyuni \
ubuntu-2004-amd64-main-security-uyuni \
ubuntu-2004-amd64-universe-uyuni \
ubuntu-2004-amd64-universe-updates-uyuni \
ubuntu-2004-amd64-uyuni-client
>>>>>>> 4fd527fc... Updates for Ubuntu 20.04 (#243)
----


[IMPORTANT]
====
You need all the new channels fully syncronized, including Universe (Universe contains important dependencies for salt), before bootstraping any Ubuntu client.
====
endif::[]


[NOTE]
====
{ubuntu} channels can be very large.
Synchronization can sometimes take several hours.
====

<<<<<<< HEAD
=======


== Monitor Synchronization Progress

>>>>>>> 4fd527fc... Updates for Ubuntu 20.04 (#243)
There are two ways to check if a channel has finished synchronizing:

* In the {productname} {webui}, navigate to menu:Admin[Setup Wizard] and select the [guimenu]``SUSE Products`` tab.
+
This dialog displays a completion bar for each product when they are being synchronized.
* Check the synchronization log file at the command prompt with [command]``tail -f /var/log/rhn/reposync/channel-label.log``.
+
Each child channel will generate its own log during the synchronization progress.
You will need to check all the base and child channel log files to be sure that the synchronization is complete.

ifeval::[{uyuni-content} == true]

== Trust GPG Keys on Clients

By default, {ubuntu} does not trust the GPG key for {productname} {ubuntu} client tools.

The clients can be successfully bootstrapped without the GPG key being trusted.

However, they will not be able to install new client tool packages or update them.

To fix this, add this key to the [systemitem]``ORG_GPG_KEY=`` parameter in all {ubuntu} bootstrap scripts:
----
uyuni-gpg-pubkey-0d20833e.key
----

You do not need to delete any previously stored keys.

If you are bootstrapping clients from the {productname} {webui}, you will need to use a Salt state to trust the key.
Create the Salt state and assign it to the organization.
You can then use an activation key and configuration channels to deploy the key to the clients.

endif::[]

== Root Access

The root user on {ubuntu} is disabled by default.
You can enable it by editing the [filename]``sudoers`` file.



.Procedure: Granting Root User Access

. On the client, edit the [filename]``sudoers`` file:
+
----
sudo visudo
----
+
Grant [command]``sudo`` access to the user by adding this line to the [filename]``sudoers`` file. Replace [systemitem]``<user>`` with the name of the user that will be used to bootstrap the client in the {webui}:
+
----
<user>  ALL=NOPASSWD: /usr/bin/python, /usr/bin/python2, /usr/bin/python3
----

<<<<<<< HEAD
=======
[NOTE]
====
This procedure grants root access without requiring a password, which is required for registering the client.
When the client is successfully installed it will run with root privileges, so the access is no longer required.
We recommend that you remove the line from the [path]``sudoers`` file after the client has been successfully installed.
====

>>>>>>> 4fd527fc... Updates for Ubuntu 20.04 (#243)


== Register Clients

. To register your {ubuntu} clients, you will need a bootstrap repository.
Create the bootstrap repository at the command prompt, with this command:
+
----
mgr-create-bootstrap-repo
----

For more information on registering your clients, see xref:client-configuration:registration-overview.adoc[].
